### ISSUE TITLE
User Interface checklist

### ISSUE THREAD

**Issue by ashtonFlowerday** [COS301-SE-2021/Adventure-IT#274]
- [x] Register: back button
- [x] Forgot password: remove cancel, add back button
- [x] AdventureList: width
- [x] AdventureList: reduce create date size
- [x] Adventure: card around each item
- [x] Checklist: edit and delete button
- [x] ItineraryList: dates on right
- [x] ItineraryList: next entry - next one you've signed up for
- [x] ItineraryPage: sign up and drop down attendees
- [x] BudgetPage: add currency
- [x] BudgetPage: remove cards in reports
- [x] BudgetPage: icon tabs (reports/ budgets)
- [x] FriendList: search icon
- [x] FriendList: icon tabs (friend list/ friend request)
- [x] FriendList: add button -> popup search bar
- [x] Chats: wrap card in row -> pad messages
- [x] Files: buttons to icons + number of items in a row
- [x] Media: buttons to icons + number of items in a row
- [x] Documents: buttons to icons + number of items in a row
- [x] Profile: icons instead of buttons
- [x] Settings: themes
- [x] Settings: emergency contact + geolocation
